import ConvexClientProvider from "@/components/ConvexClientProvider";
import PlanBadge from "@/components/PlanBadge";
import PlanSync from "@/components/PlanSync";
import { getClerkPublishableKey, hasClerkPublishableKey } from "@/lib/clerkConfig";
import type { Metadata } from "next";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

const AppChrome = ({
  children,
  isClerkConfigured,
}: {
  children: React.ReactNode;
  isClerkConfigured: boolean;
}) => (
  <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-50 text-zinc-900`}
    >
      <div className="min-h-screen">
        <header className="flex flex-col gap-4 border-b border-zinc-200 bg-white px-6 py-5 shadow-sm">
          <div className="flex flex-wrap items-center gap-3">
            {isClerkConfigured ? (
              <>
                <SignedOut>
                  <div className="flex flex-wrap items-center gap-3">
                    <SignInButton mode="modal">
                      <button className="text-sm font-semibold text-zinc-900 underline-offset-4 hover:underline">
                        Sign in
                      </button>
                    </SignInButton>
                    <span className="text-sm text-zinc-400">/</span>
                    <SignUpButton mode="modal">
                      <button className="text-sm text-zinc-700 underline-offset-4 hover:underline">
                        Sign up
                      </button>
                    </SignUpButton>
                  </div>
                </SignedOut>
                <SignedIn>
                  <div className="flex items-center gap-3">
                    <PlanBadge />
                    <PlanSync />
                    <UserButton />
                  </div>
                </SignedIn>
              </>
            ) : (
              <span className="text-sm text-amber-600">
                Clerk disabled (missing env). Local mode active.
              </span>
            )}
          </div>
          <div>
            <p className="text-sm font-medium text-zinc-500">
              Authentication demo
            </p>
            <h1 className="text-lg font-semibold text-zinc-900">
              Clerk + Next.js
            </h1>
          </div>
        </header>
        <main className="mx-auto max-w-4xl px-6 py-10">{children}</main>
      </div>
    </body>
  </html>
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const clerkPublishableKey = getClerkPublishableKey();
  const isClerkConfigured = hasClerkPublishableKey();

  if (!isClerkConfigured) {
    return <AppChrome isClerkConfigured={false}>{children}</AppChrome>;
  }

  return (
    <ClerkProvider
      publishableKey={clerkPublishableKey}
      afterSignOutUrl="https://accounts.cookadeli.com"
      signInUrl={clerkPublishableKey ? undefined : "https://accounts.cookadeli.com/sign-in"}
      signUpUrl={clerkPublishableKey ? undefined : "https://accounts.cookadeli.com/sign-up"}
    >
      <ConvexClientProvider>
        <AppChrome isClerkConfigured>{children}</AppChrome>
      </ConvexClientProvider>
    </ClerkProvider>
  );
}
